In [2]:
# !pip install fredapi
# !pip install altair

Collecting fredapi
  Using cached fredapi-0.5.0-py3-none-any.whl (11 kB)
Requirement already satisfied: pandas in /home/dl_/miniconda3/envs/w207_project/lib/python3.8/site-packages (from fredapi) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/dl_/miniconda3/envs/w207_project/lib/python3.8/site-packages (from pandas->fredapi) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/dl_/miniconda3/envs/w207_project/lib/python3.8/site-packages (from pandas->fredapi) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in /home/dl_/miniconda3/envs/w207_project/lib/python3.8/site-packages (from pandas->fredapi) (1.22.3)
Requirement already satisfied: six>=1.5 in /home/dl_/miniconda3/envs/w207_project/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->fredapi) (1.16.0)
Installing collected packages: fredapi
Successfully installed fredapi-0.5.0

In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn; seaborn.set()
import altair as alt
from fredapi import Fred


%matplotlib inline
pd.options.display.max_colwidth = 60

/home/dl_/miniconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
#https://github.com/chekos/altair_themes_blog/blob/master/notebooks/vox_theme.py

def vox_theme():
    markColor = '#3e5c69'
    
    return {
        'config': {
            'background': '#fff',
            'arc': { 
                'fill': markColor 
            },
            'area': { 
                'fill': markColor 
            },
            'line': { 
                'stroke': markColor 
            },
            'path': { 
                'stroke': markColor 
            },
            'rect': { 
                'fill': markColor 
            },
            'shape': { 
                'stroke': markColor 
            },
            'symbol': { 
                'fill': markColor 
            },
            'axis': {
                'domainWidth': 0.5,
                'grid': True,
                'labelPadding': 2,
                'tickSize': 5,
                'tickWidth': 0.5,
                'titleFontWeight': 'normal',
            },
            'axisBand': {
                'grid': False,
            },
            'axisX': {
                'gridWidth': 0.2,
            },  
            'axisY': {
                'gridDash': [3],
                'gridWidth': 0.4,
            },
            'legend': {
                'labelFontSize': 11,
                'padding': 1,
                'symbolType': 'square',
            },
            'range': {
                'category': [
                    '#30a2da',
                    '#fc4f30',
                    '#2000ee',
                    '#6d904f',
                    '#8b8b8b',
                    '#b96db8',
                    '#ff9e27',
                    '#56cc60',
                    '#52d2ca',
                    '#52689e',
                    '#545454',
                    '#9fe4f8',
                ],
            },
        }
        
    }

import altair as alt

# register the custom theme under a chosen name
alt.themes.register('vox_theme', vox_theme)

# enable the newly registered theme
alt.themes.enable('vox_theme')

ThemeRegistry.enable('vox_theme')

In [3]:
fred_api_key = 'bf82e24f3c920eba1ee7a46d6940f1a7'
fred = Fred(api_key=fred_api_key)

# Finding Features:

In [42]:
# search for macroeconomic indicators:

# search_term = 'consumer'

df_search = fred.search(text='commodities')
df_search = df_search[df_search['frequency_short'] == 'D'].sort_values(by='popularity', ascending=False)
#df_search.sort_values(by='popularity', ascending = False)
df_search.T

series id,DCOILWTICO,DCOILBRENTEU,DPROPANEMBTX,DJFUELUSGULF,DHOILNYH,DDFUELUSGULF,DGASUSGULF,DDFUELNYH
id,DCOILWTICO,DCOILBRENTEU,DPROPANEMBTX,DJFUELUSGULF,DHOILNYH,DDFUELUSGULF,DGASUSGULF,DDFUELNYH
realtime_start,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00
realtime_end,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00,2022-07-27 00:00:00
title,Crude Oil Prices: West Texas Intermediate (WTI) - Cushin...,Crude Oil Prices: Brent - Europe,"Propane Prices: Mont Belvieu, Texas",Kerosene-Type Jet Fuel Prices: U.S. Gulf Coast,No. 2 Heating Oil Prices: New York Harbor,Ultra-Low-Sulfur No. 2 Diesel Fuel Prices: U.S. Gulf Coast,"Conventional Gasoline Prices: U.S. Gulf Coast, Regular",Ultra-Low-Sulfur No. 2 Diesel Fuel Prices: New York Harbor
observation_start,1986-01-02 00:00:00,1987-05-20 00:00:00,1992-07-09 00:00:00,1990-04-02 00:00:00,1986-06-02 00:00:00,2006-06-14 00:00:00,1986-06-02 00:00:00,2006-06-14 00:00:00
observation_end,2022-07-25 00:00:00,2022-07-25 00:00:00,2022-07-25 00:00:00,2022-07-25 00:00:00,2022-07-25 00:00:00,2022-07-25 00:00:00,2022-07-25 00:00:00,2022-07-25 00:00:00
frequency,Daily,Daily,Daily,Daily,Daily,Daily,Daily,Daily
frequency_short,D,D,D,D,D,D,D,D
units,Dollars per Barrel,Dollars per Barrel,Dollars per Gallon,Dollars per Gallon,Dollars per Gallon,Dollars per Gallon,Dollars per Gallon,Dollars per Gallon
units_short,$ per Barrel,$ per Barrel,$ per Gallon,$ per Gallon,$ per Gallon,$ per Gallon,$ per Gallon,$ per Gallon
seasonal_adjustment,Not Seasonally Adjusted,Not Seasonally Adjusted,Not Seasonally Adjusted,Not Seasonally Adjusted,Not Seasonally Adjusted,Not Seasonally Adjusted,Not Seasonally Adjusted,Not Seasonally Adjusted
seasonal_adjustment_short,NSA,NSA,NSA,NSA,NSA,NSA,NSA,NSA
last_updated,2022-07-27 12:17:01-05:00,2022-07-27 12:17:03-05:00,2022-07-27 12:17:03-05:00,2022-07-27 12:17:04-05:00,2022-07-27 12:17:04-05:00,2022-07-27 12:17:05-05:00,2022-07-27 12:17:05-05:00,2022-07-27 12:17:06-05:00
popularity,82,74,52,42,41,37,28,24
notes,"Definitions, Sources and Explanatory Notes (http://www.e...","Definitions, Sources and Explanatory Notes (http://www.e...","Definitions, Sources and Explanatory Notes: http://www.e...","Definitions, Sources and Explanatory Notes: http://www.e...","Definitions, Sources and Explanatory Notes: http://www.e...","Definitions, Sources and Explanatory Notes: http://www.e...","Definitions, Sources and Explanatory Notes: http://www.e...","Definitions, Sources and Explanatory Notes: http://www.e..."

# Getting Data:

In [43]:
df = {}

df['S&P'] = fred.get_series('SP500') # Daily Close
# df['gdp'] = fred.get_series('GDP') # Gross Domestic Product, SA
# df['M2SL'] = fred.get_series('M2SL') # M2 (money supply), SA 
df['DFF'] = fred.get_series('DFF') # Federal Funds Effective Rate (DFF), daily
df['DGS3MO'] = fred.get_series('DGS3MO') # 3 month treasury yield
df['DGS6MO'] = fred.get_series('DGS6MO') # 6 month treasury yield
df['DGS10'] = fred.get_series('DGS10') # 10 yr treasury yield
df['BAMLH0A0HYM2'] = fred.get_series('BAMLH0A0HYM2') # tracks the performance of US dollar denominated below investment grade rated corporate debt publicly issued in the US domestic market.
# df['CPI'] = fred.get_series('CPALTT01USM661S') # Consumer Price Index: Total All Items for the United States, SA
# df['PPIACO'] = fred.get_series('CPALTT01USM661S') # PPI all commodities, NOT SA !!
# df['PAYEMS'] = fred.get_series('PAYEMS') # All Employees, Total Nonfarm, SA
# df['UNRATE'] = fred.get_series('UNRATE') # Unemployment rate, SA
# df['UMCSENT'] =fred.get_series('UMCSENT') # UMICH Consumer Sentiment, NOT SA!!
df['VXIBMCLS'] =fred.get_series('VXIBMCLS') # CBOE VIX (daily)
df['USEPUINDXD'] = fred.get_series('USEPUINDXD') # The daily news-based Economic Policy Uncertainty Index is based on newspapers in the United States.
df['DCOILWTICO'] = fred.get_series('DCOILWTICO') # Crude Oil Prices: West Texas Intermediate (WTI), daily


df = pd.DataFrame(df)
df = df.rename_axis('dt').reset_index()

In [6]:
df.dtypes

dt              datetime64[ns]
S&P                    float64
gdp                    float64
M2SL                   float64
FEDFUNDS               float64
DGS3MO                 float64
DGS6MO                 float64
DGS10                  float64
BAMLH0A0HYM2           float64
CPI                    float64
PPIACO                 float64
PAYEMS                 float64
UNRATE                 float64
UMCSENT                float64
dtype: object

#### Lots of missing dates between reporting of macroeconomic data

In [44]:
pd.date_range(start = '1939-01-01', end = '2022-07-18' ).difference(df.index)

DatetimeIndex(['1939-01-01', '1939-01-02', '1939-01-03', '1939-01-04',
               '1939-01-05', '1939-01-06', '1939-01-07', '1939-01-08',
               '1939-01-09', '1939-01-10',
               ...
               '2022-07-09', '2022-07-10', '2022-07-11', '2022-07-12',
               '2022-07-13', '2022-07-14', '2022-07-15', '2022-07-16',
               '2022-07-17', '2022-07-18'],
              dtype='datetime64[ns]', length=30515, freq='D')

# EDA : Missing value - count and percentage

In [45]:
print('Null Values Present: ', df.isnull().values.sum())

Null Values Present:  128149

In [46]:
count_missing = df.isnull().sum()
percent_missing = df.isnull().sum() * 100 / len(df)

missing_value_df = pd.DataFrame(
    {'count_missing': count_missing,
     'percent_missing': percent_missing}
)
missing_value_df

              count_missing  percent_missing
dt                        0         0.000000
S&P                   22348        89.884567
DFF                       1         0.004022
DGS3MO                14639        58.878655
DGS6MO                14639        58.878655
DGS10                  9737        39.162611
BAMLH0A0HYM2          18189        73.156900
VXIBMCLS              21803        87.692555
USEPUINDXD            11142        44.813578
DCOILWTICO            15651        62.948960

In [47]:
df[df['DGS10'].isnull()]

,dt,S&P,DFF,DGS3MO,DGS6MO,DGS10,BAMLH0A0HYM2,VXIBMCLS,USEPUINDXD,DCOILWTICO
0,1954-07-01,NaN,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1954-07-02,NaN,1.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1954-07-03,NaN,1.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1954-07-04,NaN,1.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1954-07-05,NaN,0.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
24852,2022-07-16,NaN,1.58,NaN,NaN,NaN,NaN,NaN,217.33,NaN
24853,2022-07-17,NaN,1.58,NaN,NaN,NaN,NaN,NaN,193.74,NaN
24859,2022-07-23,NaN,1.58,NaN,NaN,NaN,NaN,NaN,96.97,NaN
24860,2022-07-24,NaN,1.58,NaN,NaN,NaN,NaN,NaN,212.51,NaN
24862,2022-07-26,3921.05,NaN,NaN,NaN,NaN,5.06,25.24,30.93,NaN

In [48]:
df[df['DCOILWTICO'].notnull()]

,dt,S&P,DFF,DGS3MO,DGS6MO,DGS10,BAMLH0A0HYM2,VXIBMCLS,USEPUINDXD,DCOILWTICO
11508,1986-01-02,NaN,8.76,7.33,7.50,9.04,NaN,NaN,161.63,25.56
11509,1986-01-03,NaN,8.34,7.29,7.49,9.05,NaN,NaN,56.10,26.00
11512,1986-01-06,NaN,8.00,7.29,7.47,9.07,NaN,NaN,114.81,26.53
11513,1986-01-07,NaN,7.82,7.26,7.43,8.94,NaN,NaN,198.20,25.85
11514,1986-01-08,NaN,7.79,7.40,7.58,9.13,NaN,NaN,73.31,25.87
...,...,...,...,...,...,...,...,...,...,...
24855,2022-07-19,3936.69,1.58,2.52,3.06,3.01,5.10,27.65,179.13,106.12
24856,2022-07-20,3959.90,1.58,2.51,3.04,3.04,4.90,25.86,114.88,104.45
24857,2022-07-21,3998.95,1.58,2.48,3.00,2.91,4.99,26.18,129.00,98.44
24858,2022-07-22,3961.63,1.58,2.49,2.97,2.77,4.96,25.73,143.51,97.71
24861,2022-07-25,3966.84,1.58,2.62,3.06,2.81,4.95,25.17,110.63,99.83

In [49]:
# forward fill to impute missing data, drop NA to drop dates where records didn't start.

df_ff = df.ffill().dropna() 
df_ff

,dt,S&P,DFF,DGS3MO,DGS6MO,DGS10,BAMLH0A0HYM2,VXIBMCLS,USEPUINDXD,DCOILWTICO
21211,2012-07-27,1385.97,0.14,0.11,0.15,1.58,6.22,19.04,128.12,90.13
21212,2012-07-28,1385.97,0.14,0.11,0.15,1.58,6.22,19.04,115.78,90.13
21213,2012-07-29,1385.97,0.14,0.11,0.15,1.58,6.22,19.04,182.58,90.13
21214,2012-07-30,1385.30,0.14,0.11,0.15,1.53,6.20,19.50,166.93,89.80
21215,2012-07-31,1379.32,0.13,0.11,0.14,1.51,6.16,19.85,109.48,88.08
...,...,...,...,...,...,...,...,...,...,...
24858,2022-07-22,3961.63,1.58,2.49,2.97,2.77,4.96,25.73,143.51,97.71
24859,2022-07-23,3961.63,1.58,2.49,2.97,2.77,4.96,25.73,96.97,97.71
24860,2022-07-24,3961.63,1.58,2.49,2.97,2.77,4.96,25.73,212.51,97.71
24861,2022-07-25,3966.84,1.58,2.62,3.06,2.81,4.95,25.17,110.63,99.83
24862,2022-07-26,3921.05,1.58,2.62,3.06,2.81,5.06,25.24,30.93,99.83

In [51]:
count_missing = df_ff.isnull().sum()
percent_missing = df_ff.isnull().sum() * 100 / len(df_ff)

missing_value_df = pd.DataFrame(
    {'count_missing': count_missing,
     'percent_missing': percent_missing}
)
missing_value_df

              count_missing  percent_missing
dt                        0              0.0
S&P                       0              0.0
DFF                       0              0.0
DGS3MO                    0              0.0
DGS6MO                    0              0.0
DGS10                     0              0.0
BAMLH0A0HYM2              0              0.0
VXIBMCLS                  0              0.0
USEPUINDXD                0              0.0
DCOILWTICO                0              0.0

In [52]:
df_ff.to_csv('macro_data_daily.csv')

In [ ]:
df_ff.set_index('dt').loc['2020-01-01':'2022-07-01']