In [1]:
import pandas as pd
import time
from better_profanity import profanity
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import date

In [3]:
def create_df(csv_file, search = None, start_date = None, end_date = None):
    # read in file
    df = pd.read_csv(csv_file, low_memory=False)
    # filter to columns of interest
    df = df[['author', 'created_utc', 'body', 'score', 'subreddit']]
    # update date format from epoch
    df['created_utc'] = pd.to_datetime(df['created_utc'],  errors='coerce')
    # drop any columns that are all N/A
    df1 = df.dropna(how='all', axis=1)
    # drop any rows for comments that were deleted
    df2 = df1.drop(df1[(df1.body == '[deleted]') | (df1.body == '[removed]') ].index)
    # drop any rows with negative scores
    df2 = df2.drop(df2[(df2.score <= 0)].index)
    # filter to comments related to stock of interest
    if search is not None:
        df3 = df2[df2['body'].str.contains(search, na=False)]
    else:
        df3 = df2
    
    # if user entered a date range
    # this is still WIP. can't get the dates to compare correctly yet
    if start_date is not None and end_date is not None:
        # update date format
        df3['created_utc'] = pd.to_datetime(df3['created_utc']).dt.date
        # filter by date range
        start_date = datetime.strptime(start_date, '%Y-%m-%d')
        end_date = datetime.strptime(end_date, '%Y-%m-%d')
        df4 = df3.loc[(df3['created_utc'] >= start_date) | (df3['created_utc'] <= end_date)]
    else:
        df4 = df3
    
#     # duplicate comment column for censoring
#     df4['body_clean'] = df4['body'] 
#     #censor the comment
#         for idx, row in df4.iterrows():
#             text = df4.loc[idx,'body_clean']
#             df4.loc[idx,'body_clean'] = profanity.censor(text)
#     # print dataframe
    return df4

# if using a google drive url (must be unzipped)
url = 'https://drive.google.com/file/d/1LnJXQR4-W03y1RFliBSZzOIVsQcy_osF/view?usp=sharing'
url = 'https://drive.google.com/uc?id=' + url.split('/')[-2]
# search should be formatted like 'pepsi|Pepsi|PEP'
# date should be formatted YYYY/MM/DD
final_df = create_df('D:/2018-2019.csv')
final_df

,author,created_utc,body,score,subreddit
1,08371A,2018-01-01 00:00:54,Bless you,6.0,wallstreetbets
2,Dick_Cuckingham,2018-01-01 00:02:28,Long winded clickbait ad.,26.0,wallstreetbets
3,Shauncore,2018-01-01 00:02:42,And that's part of the point. SPY isn't just a...,11.0,wallstreetbets
4,Shauncore,2018-01-01 00:03:25,"Undergrad, grad school, the CFA exam, and Google.",6.0,wallstreetbets
6,watchthegaps,2018-01-01 00:04:20,AAPL\nMTCH\nAMD\nDIS,1.0,wallstreetbets
...,...,...,...,...,...
5308862,omgoptions,2019-12-31 23:58:51,Wow thank you for the positive feedback. Its r...,2.0,wallstreetbets
5308863,[deleted],2019-12-31 23:58:52,And that’s enough internet for today,1.0,wallstreetbets
5308864,[deleted],2019-12-31 23:58:56,33ish? Thx Obama.,30.0,wallstreetbets
5308865,phoq5,2019-12-31 23:59:12,zaddi?,3.0,wallstreetbets
5308866,[deleted],2019-12-31 23:59:23,Lol.,18.0,wallstreetbets

In [7]:
final_df.to_csv('D:/df_2018-2019.csv')

In [16]:
a = final_df['author'].value_counts().sort_index()
a.sort_values(ascending=False)

[deleted]          10147
AnusBlaster5000      787
fartbiscuit          742
Gahvynn              713
realister            622
                   ...
SrpskaZemlja           1
omgzrob                1
omgwot                 1
omfghi2u               1
zzteddy                1
Name: author, Length: 13949, dtype: int64

In [17]:
d = final_df['created_utc'] = pd.to_datetime(final_df['created_utc']).dt.date
d.value_counts().sort_index()

2018-07-01     1921
2018-07-02     4203
2018-07-03     4459
2018-07-04     2439
2018-07-05     4074
2018-07-06     4470
2018-07-07     2190
2018-07-08     2638
2018-07-09     4441
2018-07-10     4629
2018-07-11     4611
2018-07-12     4889
2018-07-13     4047
2018-07-14     1845
2018-07-15     1911
2018-07-16     5100
2018-07-17     4643
2018-07-18     4853
2018-07-19     4965
2018-07-20     5116
2018-07-21     1683
2018-07-22     1681
2018-07-23     4162
2018-07-24     4727
2018-07-25     8379
2018-07-26    10776
2018-07-27     7581
2018-07-28     2953
2018-07-29     2996
2018-07-30     5967
2018-07-31     6937
Name: created_utc, dtype: int64

In [18]:
final_df.sort_values('score', ascending=False)

,author,created_utc,body,score,subreddit
113934,emanresu61,2018-07-26,1. Fuck You\n2. Save some money for taxes or y...,10128,wallstreetbets
74354,juicegod101,2018-07-18,Had to double check whether he actually tweete...,9122,wallstreetbets
113811,yeeee333,2018-07-26,"So you threw $64K on a FB earnings YOLO, and d...",5382,wallstreetbets
113989,MackMizzo,2018-07-26,You've got two options now:\n\nChase your high...,4856,wallstreetbets
114367,boofone,2018-07-26,"Actually, if he loses it before the end of the...",4743,wallstreetbets
...,...,...,...,...,...
54731,[deleted],2018-07-13,[removed],1,wallstreetbets
54730,[deleted],2018-07-13,[removed],1,wallstreetbets
111252,fixedelineation,2018-07-26,"Why not both, or neither who cares. Facebook i...",1,wallstreetbets
54727,[deleted],2018-07-13,[removed],1,wallstreetbets
150801,Kim_Jung_pUn,2018-07-31,"They have IP, and a listener base, clearly.",1,wallstreetbets